ifeq ($(OS), Windows_NT)
SOURCE_PATH := C:\Library\xPro\src\xpro-cli
else
SOURCE_PATH := /Library/xPro/src/xpro-cli
endif

VERSION_STRING := "\"$(shell git tag -l --sort=-creatordate | head -n 1)\""

ifeq ($(OS), Windows_NT)
BUILD_HASH := "\"$(python3 C:\Library\xPro\_uuid.py; echo;)\""
else
BUILD_HASH := "\"$(shell /Library/xPro/_uuid.py)\""
endif
 