ifeq ($(OS), Windows_NT)
SOURCE_PATH := C:\Library\xPro\src\xpro-cli
else
SOURCE_PATH := /Library/xPro/src/xpro-cli
endif

VERSION_STRING := "\"$(shell git tag -l --sort=-creatordate | head -n 1)\""

ifeq ($(OS), Windows_NT)
BUILD_HASH := "\"$(shell cat C:\Library\xPro\.hash; echo;)\""
else
BUILD_HASH := "\"$(shell cat /Library/xPro/.hash)\""
endif
 