#!/bin/bash
# Author: Brando

status=0
xproPath="$(dirname $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P ))";
xproCLISourcePath="src/xpro-cli/Release (mac)"; # xpro-cli source file path
binPath="$xproPath/bin";
xpBuild="xp";

pushd $xproPath >/dev/null 2>&1; # $xproPath

if [ ! -d $binPath ]; then 
    mkdir $binPath;
    status=$?;
fi 

pushd "$xproCLISourcePath"; # $xproCLISourcePath
if [ $status -eq 0 ]; then 
    echo "Building xPro CLI"
    make clean; 
    make all;
    status=$?;
fi 

if [ $status -eq 0 ]; then 
    if [ -f $binPath ]; then 
        rm -rfv $binPath;
        status=$?;
    fi 
fi 

if [ $status -eq 0 ]; then 
    cp -afv $xpBuild $binPath;
    status=$?;
fi 
popd; # $xproCLISourcePath

popd >/dev/null 2>&1; # $xproPath

if [ $status -eq 0 ]; then 
    echo "Success";
else 
    echo "Failed";
fi

exit $status;
