#!/bin/bash
# Author: Brando

status=0
xproPath="$(dirname $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P ))";
linkPath="/Library/xPro";
createLink=true;
xproPathMakeVar="XPRO_PATH";
debugMac="Debug (mac)";
xproCLISourcePath="src/xpro-cli/src"; # xpro-cli source file path

pushd $xproPath >/dev/null 2>&1; # Go to xpro path

echo "Building xPro"
pushd $xproCLISourcePath; # Go to the source file path for cli

cd "$debugMac"; # CD into the debug mac folder

buildPath="$xproPath/$xproCLISourcePath"; # base include path

# Build
make clean;
make all $xproPathMakeVar=$buildPath;

status=$?;

popd;
popd >/dev/null 2>&1;

if [ $status -eq 0 ]; then 
    echo "Success";
else 
    echo "Failed";
fi

exit $status;
