#!/bin/bash
# Author: Brando

status=0
xproPath="$(dirname $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P ))";
xproCLISourcePath="src/xpro-cli/Debug (mac)"; # xpro-cli source file path

pushd $xproPath >/dev/null 2>&1; # $xproPath
echo $(pwd);

pushd "$xproCLISourcePath"; # $xproCLISourcePath
if [ $status -eq 0 ]; then 
    echo "Building xPro CLI"
    make clean; 
    make all;
fi 
popd; # $xproCLISourcePath

popd >/dev/null 2>&1; # $xproPath

if [ $status -eq 0 ]; then 
    echo "Success";
else 
    echo "Failed";
fi

exit $status;
