#!/bin/bash
# Author: Brando

status=0
xproLink="/Library/xPro";
xproPath="$(dirname $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P ))";

pushd $xproPath >/dev/null 2>&1; # $xproPath

if [ $EUID -ne 0 ]; then 
    echo "Please run script with sudo";
    status=1;
fi 

# Make sure that xpro link does not already exist
if [ $status -eq 0 ]; then 
    if [ -d $xproLink ]; then 
        echo "Removing $xproLink";
        rm -fv $xproLink;
        status=$?;
    fi 
fi 

popd >/dev/null 2>&1; # $xproPath

if [ $status -eq 0 ]; then 
    echo "Success";
else 
    echo "Failed";
fi 