#!/bin/bash
# Author: Brando

status=0
xproLibPath="/Library";
xproLink="$xproLibPath/xPro";
xproPath="$(dirname $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P ))";

pushd $xproPath >/dev/null 2>&1; # $xproPath

if [ $EUID -ne 0 ]; then 
    echo "Please run script with sudo";
    status=1;
fi 

# Make sure that xpro link does not already exist
if [ $status -eq 0 ]; then 
    if [ -d $xproLink ]; then 
        echo "$xproLink is already a directory";
        status=1;
    elif [ -f $xproLink ]; then 
        echo "$xproLink is already a file";
        status=1;
    fi 
fi 

# Create the library directory if it 
# does not already exist
if [ $status -eq 0 ]; then 
    if [ ! -d $xproLibPath ]; then 
	mkdir -p $xproLibPath;
	status=$?;
    fi 
fi

# Create the link
if [ $status -eq 0 ]; then 
    echo "Creating link to '$xproPath' from '$xproLink'";
    ln -s $xproPath $xproLink;
    status=$?
fi 

popd >/dev/null 2>&1; # $xproPath

if [ $status -eq 0 ]; then 
    echo "Success";
else 
    echo "Failed";
fi 
